name: Test
on:
  push: 
    branches: 
      - rebuild
        
jobs:
  test:
    runs-on: ubuntu-latest   
    services:
      thor-solo:
        image: zzdockerzz/thor-solo
        ports:
          - 8669:8669
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: mocha --no-timeouts test/web3/getPastLogs.test.ts
